# Generated by Django 6.0.5 on 2026-05-07 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paypal', 'PayPal')], default='paypal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('approved', 'Approved'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='draft', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('external_order_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('capture_id', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
